### ISSUE TITLE
HTTP Code error not correct

### ISSUE THREAD

**Issue by sebastienhouzet** [urlint/urlint#22]
Hello

I have make a test :

![capture d ecran 2018-04-23 a 21 07 19](https://user-images.githubusercontent.com/2550639/39147599-6327b752-473a-11e8-806b-be2fcc367001.png)

When i see the scan result, you delete "www."

![capture d ecran 2018-04-23 a 21 07 29](https://user-images.githubusercontent.com/2550639/39147654-8c2b227e-473a-11e8-8ca7-03f3c8acaa44.png)

And you can see lot of 500, but it is not 500 but 301 :)

Have a good day :)

**Comment by Kikobeats** [comment]
After investigating looks like your site is not supporting too many concurrent requests per client.

I reduced the number of concurrent requests form 30 (the default) to 8 and it works fine:

```
urlint http://www.yoozio.com -c 8
```

Can you try it?
